---
- name: Create app directory
  ansible.builtin.file:
    path: "{{ hoprd_path }}"
    state: directory
    mode: 0777
- name: "Copy files"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - src: "{{ hoprd_identity_file }}"
      dest: "{{ hoprd_path }}/.hoprd.id"
      owner: "{{ hoprd_user }}"
      group: "{{ hoprd_group }}"
      mode: "600"
    - src: "{{ hoprd_env_file }}"
      dest: "{{ hoprd_path }}/.env-hoprd"
      owner: "{{ hoprd_user }}"
      group: "{{ hoprd_group }}"
      mode: "600"
    - src: ".env-default"
      dest: "{{ hoprd_path }}/.env-default"
      owner: "{{ hoprd_user }}"
      group: "{{ hoprd_group }}"
      mode: "600"
    - src: "hoprd.service"
      dest: "/etc/systemd/system/hoprd.service"
      owner: "{{ hoprd_user }}"
      group: "{{ hoprd_group }}"
      mode: "0644"
- name: Apply docker-compose
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ hoprd_path }}/docker-compose.yaml"
    owner: "{{ hoprd_user }}"
    group: "{{ hoprd_group }}"
    mode: "0640"
- name: Apply env file
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ hoprd_path }}/.env"
    owner: "{{ hoprd_user }}"
    group: "{{ hoprd_group }}"
    mode: "0640"
- name: Get my public IP
  community.general.ipify_facts:
- name: Add HOPRD_HOST
  lineinfile:
    dest: "{{ hoprd_path }}/.env"
    line: "HOPRD_HOST={{ ipify_public_ip }}:9091"
    state: present
- name: reload systemctl
  ansible.builtin.systemd:
    daemon_reload: true
- name: Start Hoprd service
  ansible.builtin.service:
    name: "hoprd.service"
    state: restarted
    enabled: true
