---
- name: Create app directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  with_items:
    - "{{ hoprd_path }}/config"
    - "{{ hoprd_path }}/metrics"
    - "{{ hoprd_path }}/fluentbit"
    - "{{ hoprd_path }}/data"
- name: "Copy files"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ hoprd_user }}"
    group: "{{ hoprd_group }}"
    mode: "{{ item.mode }}"
  with_items:
    - src: "{{ hoprd_identity_file }}"
      dest: "{{ hoprd_path }}/config/.hoprd.id"
      mode: "600"
    - src: "{{ hoprd_fluentbit_ca_file }}"
      dest: "{{ hoprd_path }}/fluentbit/ca.crt"
      mode: "600"
    - src: "{{ hoprd_fluentbit_crt_file }}"
      dest: "{{ hoprd_path }}/fluentbit/tls.crt"
      mode: "600"
    - src: "{{ hoprd_fluentbit_key_file }}"
      dest: "{{ hoprd_path }}/fluentbit/tls.key"
      mode: "600"
    - src: "flatten_spans.lua"
      dest: "{{ hoprd_path }}/fluentbit/flatten_spans.lua"
      mode: "755"
    - src: "truncate.lua"
      dest: "{{ hoprd_path }}/fluentbit/truncate.lua"
      mode: "755"
    - src: "hoprd.service"
      dest: "/etc/systemd/system/hoprd.service"
      mode: "0644"
    - src: "metrics.sh"
      dest: "/opt/hoprd/metrics/metrics.sh"
      mode: "0774"
    - src: "lighttpd.conf"
      dest: "/opt/hoprd/metrics/lighttpd.conf"
      mode: "0644"
  when: item.src is defined and item.src | length > 0
- name: Get my public IP
  community.general.ipify_facts:
- name: Apply Templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ hoprd_user }}"
    group: "{{ hoprd_group }}"
    mode: "{{ item.mode }}"
  with_items:
    - src: docker-compose.yaml.j2
      dest: "{{ hoprd_path }}/docker-compose.yaml"
      mode: "0640"
    - src: hoprd.cfg.yaml.j2
      dest: "{{ hoprd_path }}/config/hoprd.cfg.yaml"
      mode: "0640"
    - src: .env.j2
      dest: "{{ hoprd_path }}/.env"
      mode: "0640"
    - src: .env-hoprd.j2
      dest: "{{ hoprd_path }}/.env-hoprd"
      mode: "0640"
    - src: fluent-bit.conf.j2
      dest: "{{ hoprd_path }}/fluentbit/fluent-bit.conf"
      mode: "0640"
- name: reload systemctl
  ansible.builtin.systemd:
    daemon_reload: true
- name: Start Hoprd service
  ansible.builtin.service:
    name: "hoprd.service"
    state: restarted
    enabled: true
