---
- name: Create app directory
  ansible.builtin.file:
    path: "{{ hoprd_path }}/hoprd-db"
    state: directory
    mode: 0777
- name: "Copy files"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ hoprd_user }}"
    group: "{{ hoprd_group }}"
    mode: "{{ item.mode }}"
  with_items:
    - src: "{{ hoprd_identity_file }}"
      dest: "{{ hoprd_path }}/.hoprd.id"
      mode: "600"
    - src: "{{ hoprd_fluentbit_sa_file }}"
      dest: "{{ hoprd_path }}/fluent-bit-gcp-sa.json"
      mode: "600"
    - src: "hoprd.service"
      dest: "/etc/systemd/system/hoprd.service"
      mode: "0644"
    - src: "metrics.sh"
      dest: "/opt/hoprd/metrics.sh"
      mode: "0774"
    - src: "lighttpd.conf"
      dest: "/opt/hoprd/lighttpd.conf"
      mode: "0644"
  when: item.src is defined and item.src | length > 0
- name: Get my public IP
  community.general.ipify_facts:
- name: Apply Templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ hoprd_user }}"
    group: "{{ hoprd_group }}"
    mode: "{{ item.mode }}"
  with_items:
    - src: docker-compose.yaml.j2
      dest: "{{ hoprd_path }}/docker-compose.yaml"
      mode: "0640"
    - src: hoprd.cfg.yaml.j2
      dest: "{{ hoprd_path }}/hoprd.cfg.yaml"
      mode: "0640"
    - src: .env.j2
      dest: "{{ hoprd_path }}/.env"
      mode: "0640"
    - src: .env-hoprd.j2
      dest: "{{ hoprd_path }}/.env-hoprd"
      mode: "0640"
    - src: fluent-bit.conf.j2
      dest: "{{ hoprd_path }}/fluent-bit.conf"
      mode: "0640"
- name: reload systemctl
  ansible.builtin.systemd:
    daemon_reload: true
- name: Start Hoprd service
  ansible.builtin.service:
    name: "hoprd.service"
    state: restarted
    enabled: true
