name: Bump Version on PR Merge

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: write

jobs:
  bump-version:
    runs-on: self-hosted-hoprnet-small
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Bump and tag version
        run: |
          IFS='.' read -r major minor patch <<< "${{ vars.ANSIBLE_ROLE_VERSION }}"
          new_patch=$((patch + 1))
          new_version="$major.$minor.$new_patch"
          echo "New version: $new_version"
          gh variable set ANSIBLE_ROLE_VERSION --body "${new_version}"
          git tag "v${new_version}"
          git push origin "v${new_version}"
        env:
          GH_TOKEN: ${{ secrets.GH_RUNNER_TOKEN }}

